In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [40]:
df=pd.read_csv("/content/shopify_stock.csv")

In [41]:
df.head()

                        date   open   high    low  close  adj_close     volume
0  2015-05-21 00:00:00-04:00  2.800  2.874  2.411  2.568      2.568  123039000
1  2015-05-22 00:00:00-04:00  2.607  3.110  2.600  2.831      2.831   28412000
2  2015-05-26 00:00:00-04:00  2.980  3.034  2.908  2.965      2.965    8202000
3  2015-05-27 00:00:00-04:00  3.067  3.081  2.700  2.750      2.750    7976000
4  2015-05-28 00:00:00-04:00  2.755  2.774  2.648  2.745      2.745    4000000

In [42]:
df.shape

(2469, 7)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2469 entries, 0 to 2468
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   date       2469 non-null   object
 1   open       2469 non-null   float64
 2   high       2469 non-null   float64
 3   low        2469 non-null   float64
 4   close      2469 non-null   float64
 5   adj_close  2469 non-null   float64
 6   volume     2469 non-null   int64
dtypes: float64(5), int64(1), object(1)
memory usage: 135.2+ KB

In [44]:
df.describe()

,open,high,low,close,adj_close,volume
count,2469.000000,2469.000000,2469.000000,2469.000000,2469.000000,2.469000e+03
mean,48.464345,49.505495,47.347795,48.456613,48.456613,1.657049e+07
std,43.633916,44.470235,42.642546,43.573362,43.573362,1.436909e+07
min,1.939000,1.985000,1.848000,1.933000,1.933000,1.039000e+06
25%,10.479000,10.635000,10.275000,10.450000,10.450000,8.098000e+06
50%,35.640999,36.879002,34.655998,35.874001,35.874001,1.275860e+07
75%,76.080002,77.169998,74.589996,75.800003,75.800003,2.060200e+07
max,171.800003,176.291794,168.509506,169.059998,169.059998,2.089590e+08

In [45]:
df["date"] = pd.to_datetime(df["date"],utc=True)

In [46]:
df['date'].dtype

datetime64[ns, UTC]

In [47]:
print(df.isnull().sum())

date         0
open         0
high         0
low          0
close        0
adj_close    0
volume       0
dtype: int64

In [48]:
df=df.dropna()

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df=df.drop_duplicates()
df

,date,open,high,low,close,adj_close,volume
0,2015-05-21 04:00:00+00:00,2.800000,2.874000,2.411000,2.568000,2.568000,123039000
1,2015-05-22 04:00:00+00:00,2.607000,3.110000,2.600000,2.831000,2.831000,28412000
2,2015-05-26 04:00:00+00:00,2.980000,3.034000,2.908000,2.965000,2.965000,8202000
3,2015-05-27 04:00:00+00:00,3.067000,3.081000,2.700000,2.750000,2.750000,7976000
4,2015-05-28 04:00:00+00:00,2.755000,2.774000,2.648000,2.745000,2.745000,4000000
...,...,...,...,...,...,...,...
2464,2025-03-10 04:00:00+00:00,96.070000,96.186996,91.690002,92.750000,92.750000,16385300
2465,2025-03-11 04:00:00+00:00,92.750000,95.109001,91.150002,92.949997,92.949997,12127100
2466,2025-03-12 04:00:00+00:00,96.669998,99.135002,95.290001,96.529999,96.529999,8531900
2467,2025-03-13 04:00:00+00:00,95.169998,95.529999,89.099998,90.589996,90.589996,11076400
2468,2025-03-14 04:00:00+00:00,94.610001,95.830002,93.059998,94.849998,94.849998,7060700

In [51]:
df=df.sort_values("date")

In [52]:
df["Daily_delta"] =df["close"] -df["open"]

In [53]:
df["Daily_Return"]= (
    df["close"]-df["open"]/ df["open"]
)*100

In [54]:
print(df[
    ["date","open","close","Daily_delta","Daily_Return"]
      ].head())

                       date   open  close  Daily_delta  Daily_Return
0 2015-05-21 04:00:00+00:00  2.800  2.568       -0.232    156.800008
1 2015-05-22 04:00:00+00:00  2.607  2.831        0.224    183.100009
2 2015-05-26 04:00:00+00:00  2.980  2.965       -0.015    196.499991
3 2015-05-27 04:00:00+00:00  3.067  2.750       -0.317    175.000000
4 2015-05-28 04:00:00+00:00  2.755  2.745       -0.010    174.499989

In [55]:
average_volume = df["volume"].mean()
Maximum_volume =df["volume"].max()
minimum_vloume =df["volume"].min()

print("Averge_volume",average_volume)
print("Maximum_volume",Maximum_volume)

Averge_volume 16570491.778047793
Maximum_volume 208959000

In [56]:
threshold =2*average_volume

In [57]:
anomalous_days=df[df["volume"]>threshold]

In [58]:
print("\n anomalous trading days:")
anomalous_days.head()

 anomalous trading days:

,date,open,high,low,close,adj_close,volume,Daily_delta,Daily_Return
0,2015-05-21 04:00:00+00:00,2.800,2.874,2.411,2.568,2.568,123039000,-0.232,156.800008
186,2016-02-17 05:00:00+00:00,2.429,2.481,2.164,2.237,2.237,34914000,-0.192,123.699999
303,2016-08-03 04:00:00+00:00,3.497,3.715,3.320,3.679,3.679,33537000,0.182,267.899990
313,2016-08-17 04:00:00+00:00,3.890,3.957,3.860,3.874,3.874,58113000,-0.016,287.400007
410,2017-01-05 05:00:00+00:00,4.447,4.794,4.425,4.768,4.768,50702000,0.321,376.800013

In [59]:
print("Means Return:",df["Daily_Return"].mean())
print("variance:", df["Daily_Return"].var())
print("Standard Deviation:" ,df["Daily_Return"].std())

Means Return: 4745.66131869807
variance: 18986378.95691339
Standard Deviation: 4357.336222615073